backend:
  name: git-gateway
  branch: master

media_folder: "/static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: authors
    label: Authors
    folder: "authors"
    create: true
    fields:
      - {name: "name", label: "Name"}
      - {name: "bio", label: "Bio", widget: "text", required: "false"}

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - name: "author"
        label: "Author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name"]
        valueField: "name"
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "links"
    label: "Links"
    folder: "src/pages/links"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "link-post"}
      - name: "author"
        label: "Author"
        widget: "relation"
        collection: "authors"
        searchFields: ["name"]
        valueField: "name"
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "URL", name: "linkUrl", widget: "string"}
      - {label: "Image", name: "linkImage", widget: "image", required: "false"}
      - {label: "Tags", name: "tags", widget: "list", required: "false"}
      - {label: "Body", name: "body", widget: "markdown", required: "false"}

  - name: "work"
    label: "Work"
    folder: "src/pages/work"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "work-project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Project URL", name: "url", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image_featured", widget: "image"}
      - {label: "Image 1", name: "image_1", widget: "image", required: "false"}
      - {label: "Image 2", name: "image_2", widget: "image", required: "false"}
      - {label: "Image 3", name: "image_3", widget: "image", required: "false"}

  - name: "about"
    label: "About"
    folder: "src/pages/about"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
